version: '3'
services:
  zookeeper:
    image: 'zookeeper'
    ports:
      - "2181:2181"
  kafka:
    image: 'rwlv2-kafka:latest'
    depends_on:
      - zookeeper
    ports:
      - "9094:9094/tcp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  keycloak:
    image: 'rwlv2-keycloak:latest'
    ports:
      - "8580:8580"
      - "10499:10499"
    depends_on:
      - postgres
  postgres:
    image: 'rwlv2-postgres:latest'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
    - "5432:5432"
