version: '3'
services:
  zookeeper:
    image: 'zookeeper'
    ports:
      - "2181:2181"
  kafka:
    image: rwlv2-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9094:9094/tcp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
