apiVersion: v1
kind: Service
metadata:
  name: rwlv2-postgres
  labels:
    app: rwlv2
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: 32543
  selector:
    app: rwlv2
    tier: db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: rwlv2
spec:
#  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rwlv2-postgres
  labels:
    app: rwlv2
spec:
  selector:
    matchLabels:
      app: rwlv2
      tier: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rwlv2
        tier: db
    spec:
      containers:
        - image: rwlv2-postgres:local
          name: postgres
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
#              valueFrom:
#                secretKeyRef:
#                  name: postgres-pass
#                  key: password
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql/data
#              subPath: postgres
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim